## Gaussian Elimination

This is a technique for solving systems of equations.

Lets consider:
$$2x + y - 2z = 1$$
$$3x + 2y +2z = 7$$
$$5x + 4y + 3z = 12$$

We progressively eliminate each variable producing an 'upper triangular matrix'.

Coefficient matrix:

In [404]:
import numpy as np
co_matrix = np.array([[2,1,-2],
            [3,2,2],
            [5,4,3]])
print(co_matrix)

[[ 2  1 -2]
 [ 3  2  2]
 [ 5  4  3]]


In an upper triangular matrix only values **above** the main diagonal will be non zero. Vice versa for lower triangular matrix.

We attain this by row operations performed.

The augmented matrix which is a way of representing a system of linear equations with the constants on the right hand side is:

In [405]:
A = np.array([[2,1,-2,1],[3,2,2,7],[5,4,3,12]], dtype=float)
print(A)

[[ 2.  1. -2.  1.]
 [ 3.  2.  2.  7.]
 [ 5.  4.  3. 12.]]


Best practice is to want the leading coefficient of the first row to be 1.

In [406]:
A[0] = A[0] / 2
print(A)

[[ 1.   0.5 -1.   0.5]
 [ 3.   2.   2.   7. ]
 [ 5.   4.   3.  12. ]]


Then we want the first element of any nonzero row to be to the right of the first element in the row above it to get the Augmented matrix to Row echelon form.

In [407]:
A[1] = 3*A[0] - A[1]
print(A)

[[ 1.   0.5 -1.   0.5]
 [ 0.  -0.5 -5.  -5.5]
 [ 5.   4.   3.  12. ]]


In [408]:
A[2] = 5*A[0] - A[2]
print(A)

[[ 1.   0.5 -1.   0.5]
 [ 0.  -0.5 -5.  -5.5]
 [ 0.  -1.5 -8.  -9.5]]


In [409]:
A[1] = -2 * A[1]
print(A)

[[ 1.   0.5 -1.   0.5]
 [-0.   1.  10.  11. ]
 [ 0.  -1.5 -8.  -9.5]]


In [410]:
A[2] = -(2/3) * A[2]
print(A)

[[ 1.          0.5        -1.          0.5       ]
 [-0.          1.         10.         11.        ]
 [-0.          1.          5.33333333  6.33333333]]


In [411]:
A[2] = A[1] - A[2]
print(A)

[[ 1.          0.5        -1.          0.5       ]
 [-0.          1.         10.         11.        ]
 [ 0.          0.          4.66666667  4.66666667]]


In [412]:
A[2] = (3/14) * A[2]
print(A)

[[ 1.   0.5 -1.   0.5]
 [-0.   1.  10.  11. ]
 [ 0.   0.   1.   1. ]]


This is now in Row echelon form. From backward substitution:
$$1z = 1 \implies z =1$$
$$1y + 10z = 11 \implies 1y +10(1) = 11 \implies y = 1$$
$$1x + 0.5y - 1z = 0.5 \implies 1x + 0.5 -1 = 0.5 \implies x = 0.5$$

our solution set is [1,1,1].

Numpy itself provides np.linalg.solve which performs gaussian elimination.

In [413]:
a = np.array([[2,1,-2],[3,2,2],[5,4,3]])
b = np.array([1,7,12])
x = np.linalg.solve(a,b)
print(f'Solution : {x}')

Solution : [1. 1. 1.]


In [414]:
## Matrix multiplication

A = np.array([[1,2,1],
     [2,1,2]])
B = np.array([[1,2],
              [2,1],
              [1,2]])

C = A @ B
print(C)

[[6 6]
 [6 9]]


In [415]:
A = np.array([[1,2,2],
     [1,1,2],
     [1,1,1]])
B = A.transpose()
B

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 1]])

In [416]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Identity matrix - A square matrix with 1's across its **principal diaganol** and 0's in other element positions.

In [417]:
np.identity(3) * np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [418]:
A = np.array([[1,2,3],
            [3,2,1],
            [4,6,7]])
A_det = np.linalg.det(A)
print(f"determinant of A is :{A_det}")

# multiplying a row by k = 2 changes the value of the determinant k fold
A[0] = A[0] * 2
print(A)
A_det = np.linalg.det(A)
print(f"determinant of A Operated is :{A_det}")

determinant of A is :4.0
[[2 4 6]
 [3 2 1]
 [4 6 7]]
determinant of A Operated is :7.999999999999998


In [419]:
print(np.linalg.inv(A))

[[ 1.     1.    -1.   ]
 [-2.125 -1.25   2.   ]
 [ 1.25   0.5   -1.   ]]


## Inverse Matrix

The inverse of a matrix A, denoted by $A^{-1}$, is defined only if it is a square matrix, in which case the inverse is a matrix that satisfies the condition:$$ A A^{-1} = I$$

In [420]:
print(A)
a_inv = np.linalg.inv(A)
C = A @ a_inv
print(C)

[[2 4 6]
 [3 2 1]
 [4 6 7]]
[[ 1.00000000e+00  2.22044605e-16 -4.44089210e-16]
 [ 6.66133815e-16  1.00000000e+00 -6.66133815e-16]
 [ 1.55431223e-15  3.33066907e-16  1.00000000e+00]]


This is the identity matrix, as values not on the principle diagonal are extremely small. The reason why these take values and are not zero is due to floating point precision.

## Iterative Scheme

An iterative scheme is the procedure of making a guess obtaining an answer and using that answer for the next attempt.

The first method we will code is the Gauss Jacobi Method:

The prerequisite for the Gauss Jacobi method is that teh matrix is Diagonally Dominant. Whereby the value along the main diagonal value must be larger in absolute value than the sum of the other elements in the row.

In [421]:
# Check if matrix is Diagonally Dominant

def check_diagonal_dominance(matrix):
    for i in range(0, len(matrix)):
        row_sum = 0
        for j in range(0, matrix.shape[1]):
            if i != j:
                row_sum += abs(matrix[i,j])
        non_prinicipal_sum = row_sum
        if abs(matrix[i,i]) <= non_prinicipal_sum:
            print(f"Row {i} fails the diagonal dominance condition")
            return False
    return True

In [422]:
A = np.array([[2, 1, 0], 
              [1, 4, 2], 
              [1, 2, 4]])

check_diagonal_dominance(A)

True

In [423]:
def gauss_jacobi(A, b, x0, tol, max_iter):
    '''
    Solve the system of linear equations Ax = b using the Gauss-Jacobi iteration method

    Arguments:
    A(ndarray): Coefficient matrix
    b(ndarray): Right hand side vector of constants
    x0(ndarray): Initial guess for solution
    tol(float): Tolerance for convergance
    max_iter(int): Maximum number of iterations

    Returns:
    ndarray: The solution vector x
    int: Number of iterations taken
    '''
    A = A.astype(float)
    b = b.astype(float)
    x0 = x0.astype(float)

    n = len(b)
    x = np.copy(x0)
    
    for k in range(max_iter):
        x_new = np.copy(x)

        for i in range(n):
            sum_non_diagonal = 0
            for j in range(n):
                if i != j:
                    sum_non_diagonal += (A[i,j] * x[j])
            x_new[i] = (b[i] - sum_non_diagonal) / (A[i,i])

        diff = np.abs(x_new - x)
        if np.all(diff < tol):  
            print(f'Converged in {k+1} iterations.')
            return x_new, k+1
        x = np.copy(x_new)

    print(f'Did not converge within {max_iter} iterations.')
    return x, max_iter

In [424]:
# Using the example from lectures whereby
# 10x1 - x2 + 2x3     = 6
#  -x1 + 11x2 -x3 +3x4 = 25
# 2x1 - x2 + 10x3 - x4 = -11
#      3x2 - x3 + 8x4 = 15

A = np.array([[10,-1,2,0],
              [-1, 11, -1, 3],
              [2,-1,10,-1],
              [0,3,-1,8]])

b = np.array([[6],[25],[-11],[15]])

tol = 1

x0 = np.array([[0],[0],[0],[0]])

max_iter = 1000

Note we know the true solution set is [1, 2, -1, 1]

In [425]:
result, iterations = gauss_jacobi(A, b, x0, 0.00000001, 10000)
print("Solution:", result)
print("Iterations:", iterations)

Converged in 24 iterations.
Solution: [[ 1.]
 [ 2.]
 [-1.]
 [ 1.]]
Iterations: 24
